### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by jwilk**
Found mostly using [mwic](http://jwilk.net/software/mwic).

### CODE REVIEW

**Comment by tkruse** [comment]
hi, thanks, is this some kind of automated message?

**Comment by jwilk** [comment]
Yes, I'm totally a robot. :unamused:
Why do you ask? 

Re test failure on Travis, I don't think it's a regression caused by my changes, but I'm too lazy to check.

**Comment by tkruse** [comment]
Because I have not touched this code in three years, I did not think anyone would use this tool (also see first line in README.md). I have no idea whether this still works with recent versions of the other tools or not. Indeed I suspect travis fails because there were changes. I see you have a nice set of tools yourself. If you use unilint and want to become maintainter, by me guest.

**Comment by jwilk** [comment]
I'm not actually a unilint user.
I only spotted it on PyPI when looking for something different. Its description was a bit broken (which is what drew my attention), so I thought I'll fix it quickly. And then I fixed a bunch of typos, because why not.
I didn't read the README. My bad.
If you don't plan further uploads to PyPI, then you may want to manually fix the description and add the `Development Status :: 7 - Inactive` classifier.

**Comment by tkruse** [comment]
Merged, and set the pypi description as suggested.

**Comment by tkruse** [comment]
thanks anyway, sorry for the wrong impression.

**Pull request closed without merging**
